/* ---------------------------------------- */
/*   File generated by OBJ2VERTIGO v0.0.3   */
/*   Created on: 11/18/2000 16:29:19        */
/* ---------------------------------------- */

id = X-1B;
object[id].max_draw_dist	= 30000;
object[id].always_draw_dist	= 1600;

object[id].nvertices		= 92;
object[id].nfacets		= 92;
object[id].nctrl_srf		= 0;


if ((object[id].vertex = malloc(object[id].nvertices*sizeof(cartvektor))) == NULL)
{
	printf("Not enough memory\n");
	exit(1);
}

if ((object[id].facet = malloc(object[id].nfacets*sizeof(polygon_struct))) == NULL)
{
	printf("Not enough memory\n");
	exit(1);
}

facetid=object[id].facet;


/**************/
/*  Vertices  */
/************************************************************/

(object[id].vertex+0)->x = 6.4494;
(object[id].vertex+0)->y = 0.520151;
(object[id].vertex+0)->z = -24.1625;
(object[id].vertex+1)->x = 6.44938;
(object[id].vertex+1)->y = -0.244995;
(object[id].vertex+1)->z = -16.1083;
(object[id].vertex+2)->x = 6.44938;
(object[id].vertex+2)->y = 0.520151;
(object[id].vertex+2)->z = -16.1083;
(object[id].vertex+3)->x = 6.4494;
(object[id].vertex+3)->y = -0.244995;
(object[id].vertex+3)->z = -24.1625;
(object[id].vertex+4)->x = 9.67106;
(object[id].vertex+4)->y = 0.137575;
(object[id].vertex+4)->z = -24.1624;
(object[id].vertex+5)->x = 9.67106;
(object[id].vertex+5)->y = 0.137575;
(object[id].vertex+5)->z = -16.1083;
(object[id].vertex+6)->x = 6.44938;
(object[id].vertex+6)->y = 0.520151;
(object[id].vertex+6)->z = -16.1083;
(object[id].vertex+7)->x = 9.67106;
(object[id].vertex+7)->y = 0.137575;
(object[id].vertex+7)->z = -16.1083;
(object[id].vertex+8)->x = 9.67106;
(object[id].vertex+8)->y = 0.137575;
(object[id].vertex+8)->z = -24.1624;
(object[id].vertex+9)->x = 6.4494;
(object[id].vertex+9)->y = 0.520151;
(object[id].vertex+9)->z = -24.1625;
(object[id].vertex+10)->x = 22.5577;
(object[id].vertex+10)->y = 6.33928;
(object[id].vertex+10)->z = -4.02707;
(object[id].vertex+11)->x = 30.6119;
(object[id].vertex+11)->y = 5.89631;
(object[id].vertex+11)->z = -8.86976;
(object[id].vertex+12)->x = 22.5577;
(object[id].vertex+12)->y = 5.45332;
(object[id].vertex+12)->z = -4.02707;
(object[id].vertex+13)->x = 22.5577;
(object[id].vertex+13)->y = 6.33928;
(object[id].vertex+13)->z = 4.02708;
(object[id].vertex+14)->x = 22.5577;
(object[id].vertex+14)->y = 5.45332;
(object[id].vertex+14)->z = 4.02708;
(object[id].vertex+15)->x = 30.6118;
(object[id].vertex+15)->y = 5.89631;
(object[id].vertex+15)->z = 8.86976;
(object[id].vertex+16)->x = 22.5577;
(object[id].vertex+16)->y = 6.33928;
(object[id].vertex+16)->z = -4.02707;
(object[id].vertex+17)->x = 22.5577;
(object[id].vertex+17)->y = 6.33928;
(object[id].vertex+17)->z = 4.02708;
(object[id].vertex+18)->x = 30.6119;
(object[id].vertex+18)->y = 5.89631;
(object[id].vertex+18)->z = -8.86976;
(object[id].vertex+19)->x = 30.6118;
(object[id].vertex+19)->y = 5.89631;
(object[id].vertex+19)->z = 8.86976;
(object[id].vertex+20)->x = -1.60477;
(object[id].vertex+20)->y = 0.520151;
(object[id].vertex+20)->z = -4.02708;
(object[id].vertex+21)->x = 6.44939;
(object[id].vertex+21)->y = -0.244995;
(object[id].vertex+21)->z = -4.02707;
(object[id].vertex+22)->x = 6.44939;
(object[id].vertex+22)->y = 0.520151;
(object[id].vertex+22)->z = -4.02707;
(object[id].vertex+23)->x = -1.60477;
(object[id].vertex+23)->y = -0.244995;
(object[id].vertex+23)->z = -4.02708;
(object[id].vertex+24)->x = 1.41556;
(object[id].vertex+24)->y = -0.244995;
(object[id].vertex+24)->z = -24.1624;
(object[id].vertex+25)->x = 1.41556;
(object[id].vertex+25)->y = 0.520151;
(object[id].vertex+25)->z = -24.1624;
(object[id].vertex+26)->x = 6.44939;
(object[id].vertex+26)->y = 0.520151;
(object[id].vertex+26)->z = -4.02707;
(object[id].vertex+27)->x = 1.41556;
(object[id].vertex+27)->y = 0.520151;
(object[id].vertex+27)->z = -24.1624;
(object[id].vertex+28)->x = -1.60477;
(object[id].vertex+28)->y = 0.520151;
(object[id].vertex+28)->z = -4.02708;
(object[id].vertex+29)->x = -1.60476;
(object[id].vertex+29)->y = -0.244995;
(object[id].vertex+29)->z = 4.02708;
(object[id].vertex+30)->x = -17.7131;
(object[id].vertex+30)->y = 1.24438;
(object[id].vertex+30)->z = 2.4875;
(object[id].vertex+31)->x = -17.7131;
(object[id].vertex+31)->y = 1.24438;
(object[id].vertex+31)->z = -2.48752;
(object[id].vertex+32)->x = -1.60477;
(object[id].vertex+32)->y = -0.244995;
(object[id].vertex+32)->z = -4.02708;
(object[id].vertex+33)->x = -1.60476;
(object[id].vertex+33)->y = -0.244995;
(object[id].vertex+33)->z = 4.02708;
(object[id].vertex+34)->x = -17.7131;
(object[id].vertex+34)->y = 1.24438;
(object[id].vertex+34)->z = -2.48752;
(object[id].vertex+35)->x = -1.60476;
(object[id].vertex+35)->y = 7.80917;
(object[id].vertex+35)->z = 4.02708;
(object[id].vertex+36)->x = -17.7131;
(object[id].vertex+36)->y = 2.41351;
(object[id].vertex+36)->z = -2.48752;
(object[id].vertex+37)->x = -17.7131;
(object[id].vertex+37)->y = 2.41351;
(object[id].vertex+37)->z = 2.4875;
(object[id].vertex+38)->x = -1.60476;
(object[id].vertex+38)->y = 7.80917;
(object[id].vertex+38)->z = 4.02708;
(object[id].vertex+39)->x = -1.60477;
(object[id].vertex+39)->y = 7.80917;
(object[id].vertex+39)->z = -4.02708;
(object[id].vertex+40)->x = -17.7131;
(object[id].vertex+40)->y = 2.41351;
(object[id].vertex+40)->z = -2.48752;
(object[id].vertex+41)->x = -1.60477;
(object[id].vertex+41)->y = -0.244995;
(object[id].vertex+41)->z = -4.02708;
(object[id].vertex+42)->x = -1.60477;
(object[id].vertex+42)->y = 7.80917;
(object[id].vertex+42)->z = -4.02708;
(object[id].vertex+43)->x = -17.7131;
(object[id].vertex+43)->y = 2.41351;
(object[id].vertex+43)->z = -2.48752;
(object[id].vertex+44)->x = -17.7131;
(object[id].vertex+44)->y = 1.24438;
(object[id].vertex+44)->z = 2.4875;
(object[id].vertex+45)->x = -17.7131;
(object[id].vertex+45)->y = 2.41351;
(object[id].vertex+45)->z = 2.4875;
(object[id].vertex+46)->x = -17.7131;
(object[id].vertex+46)->y = 1.24438;
(object[id].vertex+46)->z = -2.48752;
(object[id].vertex+47)->x = -17.7131;
(object[id].vertex+47)->y = 2.41351;
(object[id].vertex+47)->z = 2.4875;
(object[id].vertex+48)->x = -17.7131;
(object[id].vertex+48)->y = 1.24438;
(object[id].vertex+48)->z = 2.4875;
(object[id].vertex+49)->x = 6.44939;
(object[id].vertex+49)->y = 0.520151;
(object[id].vertex+49)->z = 16.1083;
(object[id].vertex+50)->x = 9.67105;
(object[id].vertex+50)->y = 0.137575;
(object[id].vertex+50)->z = 24.1625;
(object[id].vertex+51)->x = 9.67105;
(object[id].vertex+51)->y = 0.137575;
(object[id].vertex+51)->z = 16.1083;
(object[id].vertex+52)->x = 6.44939;
(object[id].vertex+52)->y = 0.520151;
(object[id].vertex+52)->z = 24.1625;
(object[id].vertex+53)->x = 6.44939;
(object[id].vertex+53)->y = 0.520151;
(object[id].vertex+53)->z = 24.1625;
(object[id].vertex+54)->x = 6.44939;
(object[id].vertex+54)->y = -0.244995;
(object[id].vertex+54)->z = 24.1625;
(object[id].vertex+55)->x = 9.67105;
(object[id].vertex+55)->y = 0.137575;
(object[id].vertex+55)->z = 24.1625;
(object[id].vertex+56)->x = 6.44939;
(object[id].vertex+56)->y = 0.520151;
(object[id].vertex+56)->z = 16.1083;
(object[id].vertex+57)->x = 9.67105;
(object[id].vertex+57)->y = 0.137575;
(object[id].vertex+57)->z = 16.1083;
(object[id].vertex+58)->x = 6.44939;
(object[id].vertex+58)->y = -0.244995;
(object[id].vertex+58)->z = 16.1083;
(object[id].vertex+59)->x = 6.44939;
(object[id].vertex+59)->y = 0.520151;
(object[id].vertex+59)->z = 4.02708;
(object[id].vertex+60)->x = 6.44939;
(object[id].vertex+60)->y = -0.244995;
(object[id].vertex+60)->z = 4.02708;
(object[id].vertex+61)->x = -1.60476;
(object[id].vertex+61)->y = -0.244995;
(object[id].vertex+61)->z = 4.02708;
(object[id].vertex+62)->x = -1.60476;
(object[id].vertex+62)->y = 0.520151;
(object[id].vertex+62)->z = 4.02708;
(object[id].vertex+63)->x = 1.41554;
(object[id].vertex+63)->y = 0.520151;
(object[id].vertex+63)->z = 24.1625;
(object[id].vertex+64)->x = 1.41554;
(object[id].vertex+64)->y = -0.244995;
(object[id].vertex+64)->z = 24.1625;
(object[id].vertex+65)->x = 6.44939;
(object[id].vertex+65)->y = 0.520151;
(object[id].vertex+65)->z = 4.02708;
(object[id].vertex+66)->x = -1.60476;
(object[id].vertex+66)->y = 0.520151;
(object[id].vertex+66)->z = 4.02708;
(object[id].vertex+67)->x = 1.41554;
(object[id].vertex+67)->y = 0.520151;
(object[id].vertex+67)->z = 24.1625;
(object[id].vertex+68)->x = 6.44939;
(object[id].vertex+68)->y = -0.244995;
(object[id].vertex+68)->z = -4.02707;
(object[id].vertex+69)->x = -1.60476;
(object[id].vertex+69)->y = -0.244995;
(object[id].vertex+69)->z = 4.02708;
(object[id].vertex+70)->x = 6.44939;
(object[id].vertex+70)->y = -0.244995;
(object[id].vertex+70)->z = 4.02708;
(object[id].vertex+71)->x = 6.44939;
(object[id].vertex+71)->y = 7.80917;
(object[id].vertex+71)->z = 4.02708;
(object[id].vertex+72)->x = 6.44939;
(object[id].vertex+72)->y = 7.80917;
(object[id].vertex+72)->z = -4.02707;
(object[id].vertex+73)->x = -1.60476;
(object[id].vertex+73)->y = -0.244995;
(object[id].vertex+73)->z = 4.02708;
(object[id].vertex+74)->x = 6.44939;
(object[id].vertex+74)->y = -0.244995;
(object[id].vertex+74)->z = 4.02708;
(object[id].vertex+75)->x = 6.44939;
(object[id].vertex+75)->y = 7.80917;
(object[id].vertex+75)->z = 4.02708;
(object[id].vertex+76)->x = 22.5577;
(object[id].vertex+76)->y = 3.37937;
(object[id].vertex+76)->z = -4.02707;
(object[id].vertex+77)->x = 22.5577;
(object[id].vertex+77)->y = 3.37937;
(object[id].vertex+77)->z = 4.02708;
(object[id].vertex+78)->x = 22.5577;
(object[id].vertex+78)->y = 6.35942;
(object[id].vertex+78)->z = 4.02708;
(object[id].vertex+79)->x = 22.5577;
(object[id].vertex+79)->y = 6.35942;
(object[id].vertex+79)->z = -4.02707;
(object[id].vertex+80)->x = 22.5577;
(object[id].vertex+80)->y = 3.37937;
(object[id].vertex+80)->z = 4.02708;
(object[id].vertex+81)->x = 22.5577;
(object[id].vertex+81)->y = 6.35942;
(object[id].vertex+81)->z = 4.02708;
(object[id].vertex+82)->x = 26.5848;
(object[id].vertex+82)->y = 15.8633;
(object[id].vertex+82)->z = 1.56e-006;
(object[id].vertex+83)->x = 18.5306;
(object[id].vertex+83)->y = 11.8362;
(object[id].vertex+83)->z = -0.805409;
(object[id].vertex+84)->x = 18.5306;
(object[id].vertex+84)->y = 11.8362;
(object[id].vertex+84)->z = 0.805421;
(object[id].vertex+85)->x = 26.5848;
(object[id].vertex+85)->y = 7.80917;
(object[id].vertex+85)->z = 1.56e-006;
(object[id].vertex+86)->x = 18.5306;
(object[id].vertex+86)->y = 7.80917;
(object[id].vertex+86)->z = 0.805421;
(object[id].vertex+87)->x = 18.5306;
(object[id].vertex+87)->y = 7.80917;
(object[id].vertex+87)->z = -0.805409;
(object[id].vertex+88)->x = 18.5306;
(object[id].vertex+88)->y = 11.8362;
(object[id].vertex+88)->z = 0.805421;
(object[id].vertex+89)->x = 18.5306;
(object[id].vertex+89)->y = 7.80917;
(object[id].vertex+89)->z = 0.805421;
(object[id].vertex+90)->x = 26.5848;
(object[id].vertex+90)->y = 7.80917;
(object[id].vertex+90)->z = 1.56e-006;
(object[id].vertex+91)->x = 26.5848;
(object[id].vertex+91)->y = 15.8633;
(object[id].vertex+91)->z = 1.56e-006;

/***********/
/*  Faces  */
/************************************************************/

/*** Begin of wing_R ***/

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 20;
facetid->edge[1] = 21;
facetid->edge[2] = 22;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 20;
facetid->edge[1] = 23;
facetid->edge[2] = 21;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 3;
facetid->edge[1] = 24;
facetid->edge[2] = 25;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 0;
facetid->edge[1] = 3;
facetid->edge[2] = 25;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 22;
facetid->edge[1] = 3;
facetid->edge[2] = 0;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 22;
facetid->edge[1] = 21;
facetid->edge[2] = 3;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 25;
facetid->edge[1] = 23;
facetid->edge[2] = 20;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 25;
facetid->edge[1] = 24;
facetid->edge[2] = 23;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 21;
facetid->edge[1] = 23;
facetid->edge[2] = 24;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 3;
facetid->edge[1] = 21;
facetid->edge[2] = 24;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 26;
facetid->edge[1] = 27;
facetid->edge[2] = 28;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 26;
facetid->edge[1] = 9;
facetid->edge[2] = 27;
facetid++;

/*** End of wing_R ***/

/*** Begin of wing_L ***/

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 59;
facetid->edge[1] = 60;
facetid->edge[2] = 61;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 59;
facetid->edge[1] = 61;
facetid->edge[2] = 62;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 63;
facetid->edge[1] = 64;
facetid->edge[2] = 54;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 63;
facetid->edge[1] = 54;
facetid->edge[2] = 53;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 53;
facetid->edge[1] = 60;
facetid->edge[2] = 59;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 53;
facetid->edge[1] = 54;
facetid->edge[2] = 60;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 62;
facetid->edge[1] = 64;
facetid->edge[2] = 63;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 62;
facetid->edge[1] = 61;
facetid->edge[2] = 64;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 60;
facetid->edge[1] = 64;
facetid->edge[2] = 61;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 60;
facetid->edge[1] = 54;
facetid->edge[2] = 64;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 65;
facetid->edge[1] = 66;
facetid->edge[2] = 67;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 52;
facetid->edge[1] = 65;
facetid->edge[2] = 67;
facetid++;

/*** End of wing_L ***/

/*** Begin of rudder ***/

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 82;
facetid->edge[1] = 83;
facetid->edge[2] = 84;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 85;
facetid->edge[1] = 86;
facetid->edge[2] = 87;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 85;
facetid->edge[1] = 87;
facetid->edge[2] = 82;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 87;
facetid->edge[1] = 83;
facetid->edge[2] = 82;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 87;
facetid->edge[1] = 86;
facetid->edge[2] = 84;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 83;
facetid->edge[1] = 87;
facetid->edge[2] = 84;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 88;
facetid->edge[1] = 89;
facetid->edge[2] = 90;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 91;
facetid->edge[1] = 88;
facetid->edge[2] = 90;
facetid++;

/*** End of rudder ***/

/*** Begin of engine ***/

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 76;
facetid->edge[1] = 70;
facetid->edge[2] = 68;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 76;
facetid->edge[1] = 77;
facetid->edge[2] = 70;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 78;
facetid->edge[1] = 72;
facetid->edge[2] = 71;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 78;
facetid->edge[1] = 79;
facetid->edge[2] = 72;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 79;
facetid->edge[1] = 76;
facetid->edge[2] = 72;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 76;
facetid->edge[1] = 68;
facetid->edge[2] = 72;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 75;
facetid->edge[1] = 74;
facetid->edge[2] = 80;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 75;
facetid->edge[1] = 80;
facetid->edge[2] = 81;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 78;
facetid->edge[1] = 76;
facetid->edge[2] = 79;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 78;
facetid->edge[1] = 77;
facetid->edge[2] = 76;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 72;
facetid->edge[1] = 70;
facetid->edge[2] = 71;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 72;
facetid->edge[1] = 68;
facetid->edge[2] = 70;
facetid++;

/*** End of engine ***/

/*** Begin of elevator ***/

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 10;
facetid->edge[1] = 11;
facetid->edge[2] = 12;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 13;
facetid->edge[1] = 14;
facetid->edge[2] = 15;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 16;
facetid->edge[1] = 17;
facetid->edge[2] = 18;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 17;
facetid->edge[1] = 19;
facetid->edge[2] = 18;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 12;
facetid->edge[1] = 11;
facetid->edge[2] = 15;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 12;
facetid->edge[1] = 15;
facetid->edge[2] = 14;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 10;
facetid->edge[1] = 12;
facetid->edge[2] = 14;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 10;
facetid->edge[1] = 14;
facetid->edge[2] = 13;
facetid++;

/*** End of elevator ***/

/*** Begin of cockpit ***/

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 29;
facetid->edge[1] = 30;
facetid->edge[2] = 31;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 32;
facetid->edge[1] = 33;
facetid->edge[2] = 34;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 35;
facetid->edge[1] = 36;
facetid->edge[2] = 37;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 38;
facetid->edge[1] = 39;
facetid->edge[2] = 40;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 35;
facetid->edge[1] = 41;
facetid->edge[2] = 42;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 35;
facetid->edge[1] = 29;
facetid->edge[2] = 41;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 43;
facetid->edge[1] = 44;
facetid->edge[2] = 45;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 43;
facetid->edge[1] = 46;
facetid->edge[2] = 44;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 42;
facetid->edge[1] = 41;
facetid->edge[2] = 36;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 41;
facetid->edge[1] = 31;
facetid->edge[2] = 36;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 47;
facetid->edge[1] = 48;
facetid->edge[2] = 33;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 47;
facetid->edge[1] = 33;
facetid->edge[2] = 38;
facetid++;

/*** End of cockpit ***/

/*** Begin of center ***/

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 68;
facetid->edge[1] = 69;
facetid->edge[2] = 41;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 68;
facetid->edge[1] = 70;
facetid->edge[2] = 69;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 71;
facetid->edge[1] = 42;
facetid->edge[2] = 35;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 71;
facetid->edge[1] = 72;
facetid->edge[2] = 42;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 72;
facetid->edge[1] = 68;
facetid->edge[2] = 41;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 72;
facetid->edge[1] = 41;
facetid->edge[2] = 42;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 38;
facetid->edge[1] = 73;
facetid->edge[2] = 74;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 38;
facetid->edge[1] = 74;
facetid->edge[2] = 75;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 71;
facetid->edge[1] = 68;
facetid->edge[2] = 72;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 71;
facetid->edge[1] = 70;
facetid->edge[2] = 68;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 39;
facetid->edge[1] = 73;
facetid->edge[2] = 38;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 39;
facetid->edge[1] = 32;
facetid->edge[2] = 73;
facetid++;

/*** End of center ***/

/*** Begin of aileron_R ***/

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 0;
facetid->edge[1] = 1;
facetid->edge[2] = 2;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 0;
facetid->edge[1] = 3;
facetid->edge[2] = 1;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 4;
facetid->edge[1] = 5;
facetid->edge[2] = 1;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 3;
facetid->edge[1] = 4;
facetid->edge[2] = 1;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 6;
facetid->edge[1] = 7;
facetid->edge[2] = 8;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 9;
facetid->edge[1] = 6;
facetid->edge[2] = 8;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 2;
facetid->edge[1] = 1;
facetid->edge[2] = 5;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 0;
facetid->edge[1] = 4;
facetid->edge[2] = 3;
facetid++;

/*** End of aileron_R ***/

/*** Begin of aileron_L ***/

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 49;
facetid->edge[1] = 50;
facetid->edge[2] = 51;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 49;
facetid->edge[1] = 52;
facetid->edge[2] = 50;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 53;
facetid->edge[1] = 54;
facetid->edge[2] = 55;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 56;
facetid->edge[1] = 57;
facetid->edge[2] = 58;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 58;
facetid->edge[1] = 54;
facetid->edge[2] = 53;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 56;
facetid->edge[1] = 58;
facetid->edge[2] = 53;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 58;
facetid->edge[1] = 55;
facetid->edge[2] = 54;
facetid++;

facetid->color   = LIGHTGRAY;
facetid->nedges  = 3;
facetid->edge[0] = 58;
facetid->edge[1] = 57;
facetid->edge[2] = 55;
facetid++;

/*** End of aileron_L ***/

if (object[id].facet+object[id].nfacets!=facetid)
{
	printf("Incorrect number of facets\n");
	exit(1);
}

nobjects++;
